import

In [1]:
import pandas as pd

file_path = './data/raw/Positive and negative personality descriptor words dataset.xlsx'
df = pd.read_excel(file_path)

pd.set_option('display.max_columns', None)

In [2]:
df

,Personality_word,Word_length,Word_valence,N_Obs_VAL,Mean_VAL,SD_VAL,Median_VAL,Min_VAL,Max_VAL,Range_VAL,Skew_VAL,Kurtosis_VAL,SE_VAL,N_Obs_IMG,Mean_IMG,SD_IMG,Median_IMG,Min_IMG,Max_IMG,Range_IMG,Skew_IMG,Kurtosis_IMG,SE_IMG,N_Obs_FREQ,Mean_FREQ,SD_FREQ,Median_FREQ,Min_FREQ,Max_FREQ,Range_FREQ,Skew_FREQ,Kurtosis_FREQ,SE_FREQ
0,Unlovable,9,Negative,199,7.316583,11.894964,1.0,0,80,80,2.542788,8.378229,0.843212,196,40.719388,30.094856,33.5,0,100,100,0.468744,-1.028683,2.149633,197,17.126904,19.435113,10.0,0,90,90,1.576953,2.254651,1.384694
1,Cruel,5,Negative,199,7.457286,11.569593,0.0,0,70,70,2.390448,7.406393,0.820147,197,78.055838,21.394066,81.0,0,100,100,-1.324507,1.641898,1.524264,197,37.512690,25.368631,35.0,0,100,100,0.380940,-0.813861,1.807440
2,Criminal,8,Negative,199,7.768844,11.719656,1.0,0,50,50,1.649554,2.004825,0.830784,197,85.456853,20.400441,92.0,0,100,100,-2.160822,4.864315,1.453471,197,48.527919,27.804813,49.0,0,100,100,0.070479,-1.018934,1.981011
3,Monstrous,9,Negative,198,8.085859,13.240367,1.0,0,74,74,2.261555,5.827191,0.940952,197,71.467005,25.439107,77.0,5,100,95,-0.935504,-0.015855,1.812461,197,14.406091,14.966546,10.0,0,77,77,1.567279,2.697776,1.066322
4,Fraudulent,10,Negative,198,8.151515,11.000566,4.0,0,65,65,1.770094,3.934399,0.781776,195,51.856410,30.348320,50.0,0,100,100,0.075867,-1.166639,2.173288,196,27.964286,22.705105,23.0,0,100,100,0.907340,0.098191,1.621793
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,Intelligent,11,Positive,199,87.613065,12.566833,90.0,34,100,66,-0.971015,0.746209,0.890839,197,76.619289,24.333403,82.0,0,100,100,-1.533674,1.715700,1.733683,197,64.847716,22.964195,68.0,4,100,96,-0.734001,-0.113459,1.636131
296,Kind,4,Positive,199,87.673367,12.225113,90.0,53,100,47,-0.754887,-0.347085,0.866615,197,75.604061,23.116290,80.0,0,100,100,-1.120997,0.824515,1.646967,197,73.314721,20.088387,76.0,6,100,94,-1.132728,1.179041,1.431238
297,Genuine,7,Positive,199,88.683417,11.593941,91.0,32,100,68,-1.123816,1.907870,0.821873,197,49.395939,30.943589,45.0,0,100,100,0.099077,-1.235056,2.204639,197,59.507614,23.360445,64.0,0,100,100,-0.546345,-0.283421,1.664363
298,Trustworthy,11,Positive,199,89.135678,11.801245,91.0,50,100,50,-0.901307,0.067243,0.836568,197,56.126904,29.970549,60.0,0,100,100,-0.176578,-1.173748,2.135313,197,55.395939,23.105472,60.0,0,100,100,-0.409460,-0.792588,1.646197
299,Honest,6,Positive,199,89.306533,11.104713,92.0,56,100,44,-0.739185,-0.381758,0.787192,197,57.705584,30.080413,60.0,0,100,100,-0.253282,-1.091446,2.143141,197,67.761421,22.067821,70.0,0,100,100,-0.749804,0.100364,1.572267

In [3]:
selected_cols = ['Personality_word', 'Word_valence', 'Mean_VAL', 'Mean_IMG', 'Mean_FREQ']
filtered_df = df[selected_cols]
filtered_df = filtered_df.rename(columns={
    'Personality_word': 'personality_word',
    'Word_valence': 'word_valence',
    'Mean_VAL': 'mean_val',
    'Mean_IMG': 'mean_img',
    'Mean_FREQ': 'mean_freq',
})

In [4]:
filtered_df

    personality_word word_valence   mean_val   mean_img  mean_freq
0          Unlovable     Negative   7.316583  40.719388  17.126904
1              Cruel     Negative   7.457286  78.055838  37.512690
2           Criminal     Negative   7.768844  85.456853  48.527919
3          Monstrous     Negative   8.085859  71.467005  14.406091
4         Fraudulent     Negative   8.151515  51.856410  27.964286
..               ...          ...        ...        ...        ...
295      Intelligent     Positive  87.613065  76.619289  64.847716
296             Kind     Positive  87.673367  75.604061  73.314721
297          Genuine     Positive  88.683417  49.395939  59.507614
298      Trustworthy     Positive  89.135678  56.126904  55.395939
299           Honest     Positive  89.306533  57.705584  67.761421

[300 rows x 5 columns]

In [5]:
filtered_df.to_csv('./data/final/actual.csv', index=False)

# For getting average predictions

In [6]:
import pandas as pd
import os

# Directory containing CSV files
directory_path = "./data/raw/predictions/"

# List all CSV files in the directory
csv_files = [f for f in os.listdir(directory_path) if f.endswith('.csv')]

# Initialize an empty list to store dataframes
df_list = []

# Load each CSV file into a DataFrame and append it to the list
for file in csv_files:
    file_path = os.path.join(directory_path, file)
    df = pd.read_csv(file_path)
    df_list.append(df)

# If there's only one file, use that directly instead of concatenating
if len(df_list) == 1:
    combined_df = df_list[0]
else:
    # Concatenate all dataframes into one if multiple files
    combined_df = pd.concat(df_list, ignore_index=True)

# Ensure that columns that should be numeric are actually numeric
combined_df['mean_val'] = pd.to_numeric(combined_df['mean_val'], errors='coerce')
combined_df['mean_img'] = pd.to_numeric(combined_df['mean_img'], errors='coerce')
combined_df['mean_freq'] = pd.to_numeric(combined_df['mean_freq'], errors='coerce')

# Ensure data is grouped by 'Personality_word'
# Custom aggregation for Word_valence: pick the most frequent value
def most_frequent(series):
    return series.mode()[0]  # Select the first value in case of a tie

# Calculate the aggregated values
averaged_df = combined_df.groupby('personality_word', sort=False).agg({
    'word_valence': most_frequent,    # Use the custom function for Word_valence
    'mean_val': 'mean',              # Calculate mean for numeric columns
    'mean_img': 'mean',
    'mean_freq': 'mean'
}).reset_index()

# Maintain the order of appearance of Personality_word
# Extract the order of Personality_word as they first appeared
first_appearance_order = pd.Series(combined_df['personality_word']).drop_duplicates()

# Reorder the aggregated dataframe to match the first appearance order
averaged_df = averaged_df.set_index('personality_word').loc[first_appearance_order].reset_index()

# Show the averaged dataframe
averaged_df

    personality_word word_valence  mean_val  mean_img  mean_freq
0          Unlovable     negative      15.0      30.0       10.0
1              Cruel     negative      10.0      40.0       15.0
2           Criminal     negative       5.0      45.0       20.0
3          Monstrous     negative      10.0      50.0       10.0
4         Fraudulent     negative      10.0      50.0       30.0
..               ...          ...       ...       ...        ...
295      Intelligent     positive      90.0      85.0       75.0
296             Kind     positive      90.0      75.0       85.0
297          Genuine     positive      85.0      80.0       80.0
298      Trustworthy     positive      90.0      80.0       75.0
299           Honest     positive      90.0      85.0       80.0

[300 rows x 5 columns]

In [7]:
averaged_df.to_csv("./data/final/predicted.csv", index=False)